### ISSUE TITLE
Companion app corrupt

### ISSUE THREAD

**Issue by TheRealAgentK** [NYTimes/Register#59]
Tried to install the companion app on three different devices via different acquisition channels:

- direct download from GH website 
- download to laptop and then file transfer to devices

All devices allow sideloading, the ones on A8 and A9 are just saying that the app wasn't installed. My A7 device with Lineage additionally states the package appears to be corrupt.

Am I missing something here?

**Comment by wdziemia** [comment]
Using this link? https://github.com/NYTimes/Register/releases/download/0.0.1/companion-0.0.3.apk

**Comment by TheRealAgentK** [comment]
Hey @wdziemia - thanks for getting back to me so quickly.

Yes, using that link.

I just looked into the apk on my laptop as well and it opens fine as a zip file and at first glance doesn't seem to be missing anything obvious.

**Comment by wdziemia** [comment]
Can you check if those devices allow third part apps?

From google: 

Go to Settings on your phone and switch to the “general” tab
Tap on the “Security” option.
Tick the checkbox next to the “Unknown Sources” option.
Confirm the warning message by tapping on “OK”.

**Comment by TheRealAgentK** [comment]
They all do, I triple checked just now.

The Register app goes through the process of installing it and then fails at the end saying the package is corrupt.

**Comment by wdziemia** [comment]
hmmmm thats funky, let me side-load on my Pixel.  Maybe the data was corrupted, did you try downloading it again?

**Comment by TheRealAgentK** [comment]
yeah, plenty of times now :-(

**Comment by TheRealAgentK** [comment]
https://www.dropbox.com/s/09bd4pnuz9zw9d4/VID_20190108_100217.mp4?dl=0

**Comment by TheRealAgentK** [comment]
It works fine now, yes. Looking at the file, it's now ~200kb larger, too.

Must have been somehow corrupted then.

Thanks muchly for your help @wdziemia !!!

**Comment by wdziemia** [comment]
It was pesky install flag! Not a problem :)
