### ISSUE TITLE
register.json cannot be read in android q

### ISSUE THREAD

**Issue by goldstei** [nytimes/Register#73]
Register gets Permission denied trying to read register.json config file on Android Q devices. This is due to https://developer.android.com/preview/privacy/scoped-storage

**Comment by candidcold** [comment]
I think if we're able to read the config file from the resource directory of the app implementing Register this shouldn't be a problem. Hopefully. Will have to look into.

**Comment by wdziemia** [comment]
Going to tag for 1.0

**Comment by candidcold** [comment]
Closing this as the permission has been removed with the `register-app` artifact
